### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by hyperpostulate** [kushibrahim/TaskManagement#3]
Unit tests must be written for each controller, service and converter. Hence Spring Data is used, and repository layer using default implementations, repository tests are not required.

**Comment by kushibrahim** [comment]
Service Converter Layer tests is added.

**Comment by kushibrahim** [comment]
Service Layer tests is added.

**Comment by kushibrahim** [comment]
added ProcessControllerTest, TaskControllerTest and updated MetricControllerTest.

### **Tests**
%75 class coverage, %52 method coverage, %63 line coverage

**Comment by hyperpostulate** [comment]
well done.
